config/routes.rb
Rails.application.routes.draw do
  resources :payments

  root 'payments#totals'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :payer, inverse_of: :participants
  belongs_to :payment, inverse_of: :participants

  delegate :email, to: :payer
  delegate :payer_name, to: :payment, prefix: true
  delegate :name, to: :payer
end

app/models/payer.rb
class Payer < ApplicationRecord
  validates :role, inclusion: { in: proc { Payer::ROLES } }

  has_many :payments, inverse_of: :payer, dependent: :destroy
  has_many :participants, inverse_of: :payer, dependent: :destroy

  ROLES = {
    1 => 'admin',
    2 => 'viewer'
  }.freeze

  def get_role
    ROLES.fetch(role, nil)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :payment_type, inclusion: { in: proc { Payment::PAYMENT_TYPES } }

  belongs_to :payer, inverse_of: :payments
  has_many :participants, inverse_of: :payment, dependent: :destroy

  accepts_nested_attributes_for :participants

  delegate :name, to: :payer, prefix: true
  delegate :email, to: :payer

  PURCHASE = 'purchase'
  SETTLEMENT = 'settlement'
  PAYMENT_TYPES = [
    PURCHASE,
    SETTLEMENT
  ].freeze

  def purchase?
    self.payment_type == PURCHASE
  end

  def settlement?
    self.payment_type == SETTLEMENT
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => " ", :password => "  "
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def totals
    payers = Payer.all
    payer_ids = payers.collect{|p| p.id}
    @totals_hash = {}

    payers.each do |payer|
      @totals_hash.store(payer, {})
      payers.each do |payee|
        @totals_hash[payer].store(payee, 0) unless payee == payer
      end
    end
    Participant.includes(:payer, payment: :payer).each do |participant|
      if @totals_hash[participant.payer][participant.payment.payer] != 0
        old_amount = @totals_hash[participant.payer][participant.payment.payer]
        if participant.amount > @totals_hash[participant.payer][participant.payment.payer]
          @totals_hash[participant.payer][participant.payment.payer] = 0
          @totals_hash[participant.payment.payer][participant.payer] = participant.amount - old_amount
        else
          @totals_hash[participant.payer][participant.payment.payer] = old_amount - participant.amount
        end
      else
        @totals_hash[participant.payment.payer][participant.payer] += participant.amount
      end
    end

    @totals_hash.values.each do |hash|
      hash.delete_if{|k,v| v == 0}
    end
    @totals_hash.delete_if{|k,v| v.empty?}
  end

  def index
    @payment_hash = {}
    payers = Payer.all
    payer_ids = payers.collect{|p| p.id}
    Payment.includes(:participants).order('created_at desc').each do |payment|
      @payment_hash.store(payment, Hash.new())
      payer_ids.each do |id|
        @payment_hash[payment].store(id, 0)
      end
      payment.participants.each do |part|
        @payment_hash[payment].store(part.payer_id, part.amount)
      end
    end
  end

  def new
    @payment = Payment.new
    @payment_type = params[:payment_type]
    @payment.participants.build
  end

  def create
    payment = Payment.new(payment_params)
    if payment.settlement?
      participant = payment.participants.first
      participant.amount = -payment.amount
    end
    if payment.save
      if payment.purchase?
        payment.participants.each do |participant|
          UserMailer.purchase_made(participant).deliver_now 
        end
      elsif payment.settlement?
        UserMailer.settlement_made(payment).deliver_now
      end
      flash[:success] = "Created!"
      redirect_to root_path and return
    else
      flash[:error] = payment.errors.full_messages.to_sentence
      redirect_to new_payment_path and return
    end
  end

  def destroy
    payment = Payment.find(params[:id])
    participants = payment.participants
    if payment.destroy
      UserMailer.deleted_payment(payment, participants).deliver_now
      flash[:success] = "Deleted!"
    else
      flash[:error] = payment.errors.full_messages.to_sentence
    end
    redirect_to root_path and return
  end

  private

  def payment_params
    params.require(:payment).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OzExpenses</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/payment/show.slim
table
  tr
    th Name
    th Amount
    th Date
    th Payer
    th Payment Type
    - Payer.all.each do |payer|
      th
        | #{payer.name}'s Amount
  - @payment_hash.each do |payment, participants|
    tr
      td
        = payment.name
      td
        = payment.amount
      td
        = payment.date_of_payment
      td
        = payment.payer_name
      td
        = payment.payment_type
      - participants.values.each do |amount|
        td
           = amount

app/views/payments/_new_purchase.slim
h3 What did you buy?
= simple_nested_form_for @payment do |f|
  = f.input :name, label: "Name of item"
  = f.input :amount, hint: "Total amount of the purchase"
  = f.input :date_of_payment
  = f.input :payer_id, collection: Payer.all, label: "Who made the purchase?"
  = f.input :payment_type, as: :hidden, input_html: { value: @payment_type }
  = f.simple_fields_for :participants, nil, { class: 'foo' } do |builder|
    .new-participant-as-child
      | Let's add other people now
    = builder.input :payer_id, collection: Payer.all, label: "Who owes money for this purchase?"
    = builder.input :amount, hint: "How much does this person owe for this purchase?", input_html: { value: nil, class: 'participant-amount' }
    = builder.link_to_remove "Remove this participant"
  = f.link_to_add "Add a participant", :participants
  br
  br
  = link_to 'Split amount evenly', '#', remote: true, id: 'split-purchase', class: 'btn btn-info m-r-sm'
  = f.submit class: 'btn btn-success'

javascript:
  $('#split-purchase').on('click', function() {
    var ways = $('.new-participant-as-child').length + 1;
    if (ways > 0) {
      var payment = $('#payment_amount').val() / ways;
      $('.participant-amount').val(payment.toFixed(2));
      $('#payment_amount').val(parseFloat($('#payment_amount').val()).toFixed(2));
    }
  });

app/views/payments/_new_settlement.slim
h3 Who are you paying back?
= simple_nested_form_for @payment do |f|
  = f.input :name, label: "Name of item", input_html: { value: "Settling debt" }
  = f.input :amount
  = f.input :date_of_payment
  = f.input :payer_id, collection: Payer.all, label: "Who are you paying back?"
  = f.input :payment_type, as: :hidden, input_html: { value: @payment_type }
  = f.simple_fields_for :participants do |builder|
    | Time to add yourself
    = builder.input :payer_id, collection: Payer.all, hint: "Hint: this is probably you"
  br
  = f.submit class: 'btn btn-success'

app/views/payments/index.slim
.table-responsive
  table.table
    tr
      th Name
      th Amount
      th Date
      th Payer
      th Payment Type
      - Payer.all.each do |payer|
        th
          | #{payer.name}'s Amount
      th
    - @payment_hash.each do |payment, participants|
      tr class="#{'success' if payment.settlement?}"
        td
          = payment.name
        td
          = number_to_currency(payment.amount)
        td
          = payment.date_of_payment
        td
          = payment.payer_name
        td
          = payment.payment_type
        - participants.values.each do |amount|
          td
             = number_to_currency(amount) unless amount == 0
        td
          = link_to "Delete", payment_path(id: payment.id), method: :delete, data: { confirm: "Are you sure?" }

= link_to "Back to home", root_path

app/views/payments/new.slim
- if @payment_type == Payment::PURCHASE
  = render 'new_purchase'
- elsif @payment_type == Payment::SETTLEMENT
  = render 'new_settlement'
- else
  | Please #{link_to "go back home", root_path} and select a payment option from there

app/views/payments/show.slim
- if @totals_hash.present?
  - @totals_hash.each do |payee, payments|
    - payments.each do |payer, amount|
      | #{payer.name} owes #{payee.name} #{amount}
      br
- else
  | Everyone is paid up!

table
  tr
    th Name
    th Amount
    th Date
    th Payer
    th Payment Type
    - Payer.all.each do |payer|
      th
        | #{payer.name}'s Amount
    th
  - @payment_hash.each do |payment, participants|
    tr
      td
        = payment.name
      td
        = payment.amount
      td
        = payment.date_of_payment
      td
        = payment.payer_name
      td
        = payment.payment_type
      - participants.values.each do |amount|
        td
           = amount
      td
        = link_to "Delete", payment_path(id: payment.id), method: :delete, data: { confirm: "Are you sure?" }

= link_to "Add a payment", new_payment_path

app/views/payments/totals.slim
.mobile-font
  h3 Current Debts
  - if @totals_hash.present?
    - @totals_hash.each do |payee, payments|
      - payments.each do |payer, amount|
        | #{payer.name} owes #{payee.name} #{number_to_currency(amount)}
        br
  - else
    | Everyone is paid up!

  h3.mobile-small What would you like to do?
  = link_to "Note a purchase", new_payment_path(payment_type: Payment::PURCHASE), class: 'btn btn-danger m-b-xs mobile-btn homepage-buttons'
  = link_to "Settle a debt", new_payment_path(payment_type: Payment::SETTLEMENT), class: 'btn btn-success m-b-xs mobile-btn homepage-buttons'
  = link_to "View all payments", payments_path, class: 'btn btn-info mobile-btn homepage-buttons'